### ISSUE TITLE
Mime type error on fiddle example

### ISSUE THREAD

**Issue by calcutec** [rjz/backbone.associate#14]
Hi,

Love the concept and am very interested  in testing this library out on jsfiddle but am getting an error on load (in Chrome):

Refused to execute script from 'https://raw.github.com/rjz/backbone.associate/9bb262a3/src/backbone.associate.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

**Comment by rjz** [comment]
@calcutec, thanks for reporting! I've updated the fiddle to load that script from github pages instead— content-type should be delivered correctly once again.

```
$ curl -sI rjz.github.io/backbone.associate/src/backbone.associate.js \
  | grep Content-Type
Content-Type: application/javascript; charset=utf-8
```
